version: '3.8'

services:
  log-analyzer:
    image: log-analyzer:latest
    ports:
      - "80:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
    volumes:
      - uploads_data:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  uploads_data:
    driver: local
